# yml适合做以数据为中心的配置文件
spring:
  main:
    allow-bean-definition-overriding: true

person:
  # 字符串默认不用加引号,单引号会将\n作为字符串输出(转义),双引号会将\n作为换行输出(不转义)
  user-name: grubby
  boss: false
  age: 18
  birth: 2000/01/01
  interests: [篮球, 足球]
  animals: [阿猫, 阿狗]
  score: {math: 100, english: 98}
  salary:
    - 9000.0
    - 8000.0


